<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Türkçe (TR)
// Author of the language pack : MyBBTurkce.com
// Language pack translators website : https://mybbturkce.com/
// Compatible version of MyBB : 1822
// Last edited in MyBB Editor by : MyPoweR
// Last edited date : Sun, 26 Apr 2020 09:15:59 +0000
// --------------------------------------------------------------------------------

$l['boardstats'] = 'Forum İstatistikleri';
$l['new_posts'] = 'Yeni Gönderi Var';
$l['no_new_posts'] = 'Yeni Gönderi Yok';
$l['forum_closed'] = 'Forum Kapalı';
$l['forum_unapproved_posts_count'] = 'Şu an forumda {1} adet onaylanmamış gönderi bulunmaktadır.';
$l['forum_unapproved_post_count'] = 'Şu an forumda 1 adet onaylanmamış gönderi bulunmaktadır.';
$l['forum_unapproved_threads_count'] = 'Şu an forumda {1} adet onaylanmamış konu bulunmaktadır.';
$l['forum_unapproved_thread_count'] = 'Şu an forumda 1 adet onaylanmamış konu bulunmaktadır.';
$l['forumteam'] = 'Forum Ekibi';
$l['forumstats'] = 'Forum İstatistikleri';
$l['todays_birthdays'] = 'Bugün Doğanlar';
$l['birthdayhidden'] = 'Gizli';
$l['quick_login'] = 'Hızlı Giriş:';
$l['index_logout'] = 'Çıkış Yap';
$l['private_messages'] = 'Özel Mesajlar';
$l['pms_new'] = 'Son ziyaretinden bu yana {1} yeni mesajın var.';
$l['pms_unread_total'] = '(Şu an {1} okunmamış, toplam {2} mesajın bulunuyor.)';
$l['stats_posts_threads'] = 'Topluluğumuzda toplam <strong>{2}</strong> konu ve <strong>{1}</strong> gönderi bulunuyor.';
$l['stats_numusers'] = 'Kayıtlı <strong>{1}</strong> oyuncumuz var.';
$l['stats_newestuser'] = 'Aramıza en son <strong>{1}</strong> katıldı, iyi oyunlar!';
$l['stats_mostonline'] = 'Çevrimiçi rekoru: {2} saat {3} itibarıyla <strong>{1}</strong> oyuncu/kişi.';
$l['whos_online'] = 'Kimler Çevrimiçi';
$l['complete_list'] = 'Tam Liste';
$l['online_online_plural'] = 'oyuncu';
$l['online_online_singular'] = 'oyuncu';
$l['online_member_plural'] = 'oyuncu';
$l['online_member_singular'] = 'oyuncu';
$l['online_anon_plural'] = 'gizli oyuncu';
$l['online_anon_singular'] = 'gizli oyuncu';
$l['online_guest_plural'] = 'ziyaretçi';
$l['online_guest_singular'] = 'ziyaretçi';
$l['online_note'] = 'Şu an <strong>{4}</strong> oyuncu ve <strong>{8}</strong> ziyaretçi aktif.';
$l['subforums'] = 'Alt Forumlar:';
$l['board_stats_link_separator'] = ' | ';
