#!/bin/sh
set -eu

PORT_VALUE="${PORT:-10000}"

sed -i "s/Listen 80/Listen ${PORT_VALUE}/" /etc/apache2/ports.conf
sed -i "s/<VirtualHost \\*:80>/<VirtualHost *:${PORT_VALUE}>/" /etc/apache2/sites-available/000-default.conf
sed -i '/<Directory \/var\/www\/>/,/<\/Directory>/ s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf

if [ ! -f /var/www/html/inc/config.php ]; then
  cp /var/www/html/.render/config.php.tpl /var/www/html/inc/config.php
fi

settings_written="0"
if [ "${MYBB_DB_TYPE:-pgsql}" = "pgsql" ] && [ -n "${MYBB_DB_HOST:-}" ] && [ -n "${MYBB_DB_NAME:-}" ] && [ -n "${MYBB_DB_USER:-}" ]; then
  settings_written="$(
    php <<'PHP'
<?php
$host = getenv('MYBB_DB_HOST') ?: '';
$port = getenv('MYBB_DB_PORT') ?: '5432';
$name = getenv('MYBB_DB_NAME') ?: '';
$user = getenv('MYBB_DB_USER') ?: '';
$pass = getenv('MYBB_DB_PASSWORD') ?: '';
$prefix = getenv('MYBB_TABLE_PREFIX') ?: 'mybb_';
$settingsPath = '/var/www/html/inc/settings.php';
$defaultBaseUrl = getenv('MYBB_BASE_URL') ?: 'http://127.0.0.1:8000';
$overrides = array(
    'adminemail' => getenv('MYBB_ADMIN_EMAIL') ?: 'admin@localhost',
    'bbname' => getenv('MYBB_FORUM_NAME') ?: 'MyBB',
    'bburl' => $defaultBaseUrl,
    'bblanguage' => getenv('MYBB_BB_LANGUAGE') ?: 'english',
    'cplanguage' => getenv('MYBB_CP_LANGUAGE') ?: (getenv('MYBB_BB_LANGUAGE') ?: 'english'),
    'homename' => getenv('MYBB_SITE_NAME') ?: 'MyBB',
    'homeurl' => getenv('MYBB_SITE_URL') ?: $defaultBaseUrl,
    'seourls' => getenv('MYBB_SEO_URLS') ?: 'yes',
    'seourls_archive' => getenv('MYBB_SEO_URLS_ARCHIVE') ?: 'yes',
);

if ($host === '' || $name === '' || $user === '') {
    echo '0';
    exit;
}

try {
    $pdo = new PDO(
        sprintf('pgsql:host=%s;port=%s;dbname=%s', $host, $port, $name),
        $user,
        $pass,
        array(PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION)
    );

    $tableName = $prefix . 'settings';
    $exists = $pdo->prepare(
        "SELECT EXISTS (
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = 'public' AND table_name = :table_name
        )"
    );
    $exists->execute(array('table_name' => $tableName));
    if (!$exists->fetchColumn()) {
        echo '0';
        exit;
    }

    $update = $pdo->prepare(sprintf('UPDATE "%s" SET value = :value WHERE name = :name', $tableName));
    foreach ($overrides as $settingName => $settingValue) {
        $update->execute(array(
            'name' => $settingName,
            'value' => $settingValue,
        ));
    }

    $query = $pdo->query(sprintf('SELECT name, value FROM "%s" ORDER BY title ASC', $tableName));
    $settings = array();
    foreach ($query as $row) {
        $settings[$row['name']] = $row['value'];
    }

    foreach ($overrides as $settingName => $settingValue) {
        $settings[$settingName] = $settingValue;
    }

    $contents = "<?php\n/*********************************\\ \n  DO NOT EDIT THIS FILE, PLEASE USE\n  THE SETTINGS EDITOR\n\\*********************************/\n\n";
    foreach ($settings as $settingName => $settingValue) {
        $safeName = addcslashes($settingName, "\\'");
        $safeValue = addcslashes((string)$settingValue, '\\"$');
        $contents .= "\$settings['{$safeName}'] = \"{$safeValue}\";\n";
    }

    file_put_contents($settingsPath, $contents, LOCK_EX);
    echo '1';
} catch (Throwable $e) {
    echo '0';
}
PHP
  )"
fi

if [ "$settings_written" != "1" ] && [ ! -f /var/www/html/inc/settings.php ]; then
  cp /var/www/html/.render/settings.php.tpl /var/www/html/inc/settings.php
fi

db_ready="0"
if [ "${MYBB_DB_TYPE:-pgsql}" = "pgsql" ] && [ -n "${MYBB_DB_HOST:-}" ] && [ -n "${MYBB_DB_NAME:-}" ] && [ -n "${MYBB_DB_USER:-}" ]; then
  db_ready="$(
    php <<'PHP'
<?php
$host = getenv('MYBB_DB_HOST') ?: '';
$port = getenv('MYBB_DB_PORT') ?: '5432';
$name = getenv('MYBB_DB_NAME') ?: '';
$user = getenv('MYBB_DB_USER') ?: '';
$pass = getenv('MYBB_DB_PASSWORD') ?: '';
$prefix = getenv('MYBB_TABLE_PREFIX') ?: 'mybb_';

if ($host === '' || $name === '' || $user === '') {
    echo '0';
    exit;
}

try {
    $pdo = new PDO(
        sprintf('pgsql:host=%s;port=%s;dbname=%s', $host, $port, $name),
        $user,
        $pass,
        array(PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION)
    );
    $stmt = $pdo->prepare(
        "SELECT EXISTS (
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = 'public' AND table_name = :table_name
        )"
    );
    $stmt->execute(array('table_name' => $prefix . 'datacache'));
    echo $stmt->fetchColumn() ? '1' : '0';
} catch (Throwable $e) {
    echo '0';
}
PHP
  )"
fi

if [ "$db_ready" = "1" ]; then
  : > /var/www/html/install/lock
else
  rm -f /var/www/html/install/lock
fi

mkdir -p /var/www/html/cache/themes /var/www/html/uploads/avatars
chown -R www-data:www-data /var/www/html/cache /var/www/html/uploads /var/www/html/inc
chmod 775 /var/www/html/cache /var/www/html/cache/themes /var/www/html/uploads /var/www/html/uploads/avatars
chmod 664 /var/www/html/inc/config.php /var/www/html/inc/settings.php

exec "$@"
